


------------------------------------------------------------------
----- IMP_HEALTH_INDEX
------------------------------------------------------------------
drop table if exists imp_health_index;
create table imp_health_index(
         id varchar(100),
         created_at varchar(100),
         updated_at varchar(100),
         location varchar(100),
         series varchar(100),
         line_ varchar(100),
         plant varchar(100),
         station varchar(100),
         robot varchar(100),
         controller varchar(100),
         tool varchar(100),
         stud varchar(100),
         stud_extension varchar(100),
         day varchar(100),
         weld_count varchar(100),
         bodyshop_count numeric,
         bodyshop_fp_count numeric,
         bodyshop_tp_count numeric,
         assembly_shop_count numeric,
         alerts_count numeric,
         health numeric,
         extension_id varchar(100),
         stud_id_id varchar(100),
         tool_id_id varchar(100),
         tse_count numeric,
         wops_count numeric,
         alerts_score_avg numeric,
         score_avg numeric,
         ftsit_avg numeric,
         dta_avg numeric,
         fta_avg numeric,
         lmlha_avg numeric,
         lmpa_avg numeric,
         pva_avg numeric,
         sa_avg numeric,
         wca_avg numeric,
         wea_avg numeric,
         wta_avg numeric,
         wtmtlpb_avg numeric,
         wtmtlpf_avg numeric,
         wtsbmt_avg numeric,
         wtsfmt_avg numeric,
         wtsfrtalbp_avg numeric,
         wtsfsp_avg numeric,
         wva_avg numeric,
         ftsit_avg_roll_mean numeric,
         ftsit_avg_roll_mean_ratio numeric,
         alerts_score_avg_roll_mean numeric,
         alerts_score_avg_roll_mean_ratio numeric,
         dta_avg_roll_mean numeric,
         dta_avg_roll_mean_ratio numeric,
         fta_avg_roll_mean numeric,
         fta_avg_roll_mean_ratio numeric,
         lmlha_avg_roll_mean numeric,
         lmlha_avg_roll_mean_ratio numeric,
         lmpa_avg_roll_mean numeric,
         lmpa_avg_roll_mean_ratio numeric,
         pva_avg_roll_mean numeric,
         pva_avg_roll_mean_ratio numeric,
         sa_avg_roll_mean numeric,
         sa_avg_roll_mean_ratio numeric,
         score_avg_roll_mean numeric,
         score_avg_roll_mean_ratio numeric,
         wca_avg_roll_mean numeric,
         wca_avg_roll_mean_ratio numeric,
         wea_avg_roll_mean numeric,
         wea_avg_roll_mean_ratio numeric,
         wta_avg_roll_mean numeric,
         wta_avg_roll_mean_ratio numeric,
         wtmtlpb_avg_roll_mean numeric,
         wtmtlpb_avg_roll_mean_ratio numeric,
         wtmtlpf_avg_roll_mean numeric,
         wtmtlpf_avg_roll_mean_ratio numeric,
         wtsbmt_avg_roll_mean numeric,
         wtsbmt_avg_roll_mean_ratio numeric,
         wtsfmt_avg_roll_mean numeric,
         wtsfmt_avg_roll_mean_ratio numeric,
         wtsfrtalbp_avg_roll_mean numeric,
         wtsfrtalbp_avg_roll_mean_ratio numeric,
         wtsfsp_avg_roll_mean numeric,
         wtsfsp_avg_roll_mean_ratio numeric,
         wva_avg_roll_mean numeric,
         wva_avg_roll_mean_ratio numeric,
         score_count numeric      
);

-- read csv file
copy imp_health_index(
       id,
       created_at,
       updated_at,
       location,
       series,
       line_,
       plant,
       station,
       robot,
       controller,
       tool,
       stud,
       stud_extension,
       day,
       weld_count,
       bodyshop_count,
       bodyshop_fp_count,
       bodyshop_tp_count,
       assembly_shop_count,
       alerts_count,
       health,
       extension_id,
       stud_id_id,
       tool_id_id,
       tse_count,
       wops_count,
       alerts_score_avg,
       score_avg,
       ftsit_avg,
       dta_avg,
       fta_avg,
       lmlha_avg,
       lmpa_avg,
       pva_avg,
       sa_avg,
       wca_avg,
       wea_avg,
       wta_avg,
       wtmtlpb_avg,
       wtmtlpf_avg,
       wtsbmt_avg,
       wtsfmt_avg,
       wtsfrtalbp_avg,
       wtsfsp_avg,
       wva_avg,
       ftsit_avg_roll_mean,
       ftsit_avg_roll_mean_ratio,
       alerts_score_avg_roll_mean,
       alerts_score_avg_roll_mean_ratio,
       dta_avg_roll_mean,
       dta_avg_roll_mean_ratio,
       fta_avg_roll_mean,
       fta_avg_roll_mean_ratio,
       lmlha_avg_roll_mean,
       lmlha_avg_roll_mean_ratio,
       lmpa_avg_roll_mean,
       lmpa_avg_roll_mean_ratio,
       pva_avg_roll_mean,
       pva_avg_roll_mean_ratio,
       sa_avg_roll_mean,
       sa_avg_roll_mean_ratio,
       score_avg_roll_mean,
       score_avg_roll_mean_ratio,
       wca_avg_roll_mean,
       wca_avg_roll_mean_ratio,
       wea_avg_roll_mean,
       wea_avg_roll_mean_ratio,
       wta_avg_roll_mean,
       wta_avg_roll_mean_ratio,
       wtmtlpb_avg_roll_mean,
       wtmtlpb_avg_roll_mean_ratio,
       wtmtlpf_avg_roll_mean,
       wtmtlpf_avg_roll_mean_ratio,
       wtsbmt_avg_roll_mean,
       wtsbmt_avg_roll_mean_ratio,
       wtsfmt_avg_roll_mean,
       wtsfmt_avg_roll_mean_ratio,
       wtsfrtalbp_avg_roll_mean,
       wtsfrtalbp_avg_roll_mean_ratio,
       wtsfsp_avg_roll_mean,
       wtsfsp_avg_roll_mean_ratio,
       wva_avg_roll_mean,
       wva_avg_roll_mean_ratio,
       score_count)
FROM '/Users/guillem/Data/Customers/Daimler/health_index/tool_health_index.csv' DELIMITER ',' CSV HEADER;

------------------------------------------------------------------------------------------------------------
------------------ create online table with proper types
------------------------------------------------------------------------------------------------------------
drop table if exists health_index;
create table health_index(
      id varchar(100),
      stud_id varchar(20),
      tool_id varchar(100),
      day date,
      weld_count numeric,
      bodyshop_count numeric,
      bodyshop_fp_count numeric,
      bodyshop_tp_count numeric,
      assembly_shop_count numeric,
      alerts_count numeric,
      tse_count numeric,
      wops_count numeric,
      health numeric,
      alerts_score_avg numeric,
      score_avg numeric,
      ftsit_avg numeric,
      dta_avg numeric,
      fta_avg numeric,
      lmlha_avg numeric,
      lmpa_avg numeric,
      pva_avg numeric,
      sa_avg numeric,
      wca_avg numeric,
      wea_avg numeric,
      wta_avg numeric,
      wtmtlpb_avg numeric,
      wtmtlpf_avg numeric,
      wtsbmt_avg numeric,
      wtsfmt_avg numeric,
      wtsfrtalbp_avg numeric,
      wtsfsp_avg numeric,
      wva_avg numeric,
      ftsit_avg_roll_mean numeric,
      ftsit_avg_roll_mean_ratio numeric,
      alerts_score_avg_roll_mean numeric,
      alerts_score_avg_roll_mean_ratio numeric,
      dta_avg_roll_mean numeric,
      dta_avg_roll_mean_ratio numeric,
      fta_avg_roll_mean numeric,
      fta_avg_roll_mean_ratio numeric,
      lmlha_avg_roll_mean numeric,
      lmlha_avg_roll_mean_ratio numeric,
      lmpa_avg_roll_mean numeric,
      lmpa_avg_roll_mean_ratio numeric,
      pva_avg_roll_mean numeric,
      pva_avg_roll_mean_ratio numeric,
      sa_avg_roll_mean numeric,
      sa_avg_roll_mean_ratio numeric,
      score_avg_roll_mean numeric,
      score_avg_roll_mean_ratio numeric,
      wca_avg_roll_mean numeric,
      wca_avg_roll_mean_ratio numeric,
      wea_avg_roll_mean numeric,
      wea_avg_roll_mean_ratio numeric,
      wta_avg_roll_mean numeric,
      wta_avg_roll_mean_ratio numeric,
      wtmtlpb_avg_roll_mean numeric,
      wtmtlpb_avg_roll_mean_ratio numeric,
      wtmtlpf_avg_roll_mean numeric,
      wtmtlpf_avg_roll_mean_ratio numeric,
      wtsbmt_avg_roll_mean numeric,
      wtsbmt_avg_roll_mean_ratio numeric,
      wtsfmt_avg_roll_mean numeric,
      wtsfmt_avg_roll_mean_ratio numeric,
      wtsfrtalbp_avg_roll_mean numeric,
      wtsfrtalbp_avg_roll_mean_ratio numeric,
      wtsfsp_avg_roll_mean numeric,
      wtsfsp_avg_roll_mean_ratio numeric,
      wva_avg_roll_mean numeric,
      wva_avg_roll_mean_ratio numeric,
      score_count numeric);

insert into health_index(
       id,
       stud_id,
       tool_id,
       day,
       weld_count,
       bodyshop_count,
       bodyshop_fp_count,
       bodyshop_tp_count,
       assembly_shop_count,
       alerts_count,
       tse_count,
       wops_count,
       health,
       alerts_score_avg,
       score_avg,
       ftsit_avg,
       dta_avg,
       fta_avg,
       lmlha_avg,
       lmpa_avg,
       pva_avg,
       sa_avg,
       wca_avg,
       wea_avg,
       wta_avg,
       wtmtlpb_avg,
       wtmtlpf_avg,
       wtsbmt_avg,
       wtsfmt_avg,
       wtsfrtalbp_avg,
       wtsfsp_avg,
       wva_avg,
       ftsit_avg_roll_mean,
       ftsit_avg_roll_mean_ratio,
       alerts_score_avg_roll_mean,
       alerts_score_avg_roll_mean_ratio,
       dta_avg_roll_mean,
       dta_avg_roll_mean_ratio,
       fta_avg_roll_mean,
       fta_avg_roll_mean_ratio,
       lmlha_avg_roll_mean,
       lmlha_avg_roll_mean_ratio,
       lmpa_avg_roll_mean,
       lmpa_avg_roll_mean_ratio,
       pva_avg_roll_mean,
       pva_avg_roll_mean_ratio,
       sa_avg_roll_mean,
       sa_avg_roll_mean_ratio,
       score_avg_roll_mean,
       score_avg_roll_mean_ratio,
       wca_avg_roll_mean,
       wca_avg_roll_mean_ratio,
       wea_avg_roll_mean,
       wea_avg_roll_mean_ratio,
       wta_avg_roll_mean,
       wta_avg_roll_mean_ratio,
       wtmtlpb_avg_roll_mean,
       wtmtlpb_avg_roll_mean_ratio,
       wtmtlpf_avg_roll_mean,
       wtmtlpf_avg_roll_mean_ratio,
       wtsbmt_avg_roll_mean,
       wtsbmt_avg_roll_mean_ratio,
       wtsfmt_avg_roll_mean,
       wtsfmt_avg_roll_mean_ratio,
       wtsfrtalbp_avg_roll_mean,
       wtsfrtalbp_avg_roll_mean_ratio,
       wtsfsp_avg_roll_mean,
       wtsfsp_avg_roll_mean_ratio,
       wva_avg_roll_mean,
       wva_avg_roll_mean_ratio,
       score_count)
select 
       a.id,
       a.stud_id_id,
       a.tool_id_id,
       to_date(a.day,'YYYY-MM-DD'),
       a.weld_count::numeric,
       a.bodyshop_count,
       a.bodyshop_fp_count,
       a.bodyshop_tp_count,
       a.assembly_shop_count,
       a.alerts_count,
       a.tse_count,
       a.wops_count,
       a.health,
       a.alerts_score_avg,
       a.score_avg,
       a.ftsit_avg,
       a.dta_avg,
       a.fta_avg,
       a.lmlha_avg,
       a.lmpa_avg,
       a.pva_avg,
       a.sa_avg,
       a.wca_avg,
       a.wea_avg,
       a.wta_avg,
       a.wtmtlpb_avg,
       a.wtmtlpf_avg,
       a.wtsbmt_avg,
       a.wtsfmt_avg,
       a.wtsfrtalbp_avg,
       a.wtsfsp_avg,
       a.wva_avg,
       a.ftsit_avg_roll_mean,
       a.ftsit_avg_roll_mean_ratio,
       a.alerts_score_avg_roll_mean,
       a.alerts_score_avg_roll_mean_ratio,
       a.dta_avg_roll_mean,
       a.dta_avg_roll_mean_ratio,
       a.fta_avg_roll_mean,
       a.fta_avg_roll_mean_ratio,
       a.lmlha_avg_roll_mean,
       a.lmlha_avg_roll_mean_ratio,
       a.lmpa_avg_roll_mean,
       a.lmpa_avg_roll_mean_ratio,
       a.pva_avg_roll_mean,
       a.pva_avg_roll_mean_ratio,
       a.sa_avg_roll_mean,
       a.sa_avg_roll_mean_ratio,
       a.score_avg_roll_mean,
       a.score_avg_roll_mean_ratio,
       a.wca_avg_roll_mean,
       a.wca_avg_roll_mean_ratio,
       a.wea_avg_roll_mean,
       a.wea_avg_roll_mean_ratio,
       a.wta_avg_roll_mean,
       a.wta_avg_roll_mean_ratio,
       a.wtmtlpb_avg_roll_mean,
       a.wtmtlpb_avg_roll_mean_ratio,
       a.wtmtlpf_avg_roll_mean,
       a.wtmtlpf_avg_roll_mean_ratio,
       a.wtsbmt_avg_roll_mean,
       a.wtsbmt_avg_roll_mean_ratio,
       a.wtsfmt_avg_roll_mean,
       a.wtsfmt_avg_roll_mean_ratio,
       a.wtsfrtalbp_avg_roll_mean,
       a.wtsfrtalbp_avg_roll_mean_ratio,
       a.wtsfsp_avg_roll_mean,
       a.wtsfsp_avg_roll_mean_ratio,
       a.wva_avg_roll_mean,
       a.wva_avg_roll_mean_ratio,
       a.score_count
from imp_health_index a;



------------------------------------------------------------------
----- IMP_TSE_HEALTH_INDEX
------------------------------------------------------------------
drop table if exists imp_tse_health_index;
create table imp_tse_health_index(
        id                                  varchar(100),
        created_at                          varchar(100),
        updated_at                          varchar(100),
        location                            varchar(20),
        series                              varchar(20),
        lin                                 varchar(20),
        plant                               varchar(20),
        station                             varchar(20),
        robot                               varchar(20),
        controller                          varchar(20),
        tool                                varchar(20),
        stud                                varchar(20),
        stud_extension                      varchar(100),
        day                                 varchar(100),
        weld_count                          numeric,
        bodyshop_count                      numeric,
        bodyshop_fp_count                   numeric,
        bodyshop_tp_count                   numeric,
        assembly_shop_count                 numeric,
        alerts_count                        numeric,
        health                              numeric,
        extension_id                        varchar(100),
        stud_id                             varchar(100),
        tool_id                             varchar(100),
        tse_count                           numeric,
        wops_count                          numeric,
        alerts_score_avg                    numeric,
        score_avg                           numeric,
        ftsit_avg                           numeric,
        dta_avg                             numeric,
        fta_avg                             numeric,
        lmlha_avg                           numeric,
        lmpa_avg                            numeric,
        pva_avg                             numeric,
        sa_avg                              numeric,
        wca_avg                             numeric,
        wea_avg                             numeric,
        wta_avg                             numeric,
        wtmtlpb_avg                         numeric,
        wtmtlpf_avg                         numeric,
        wtsbmt_avg                          numeric,
        wtsfmt_avg                          numeric,
        wtsfrtalbp_avg                      numeric,
        wtsfsp_avg                          numeric,
        wva_avg                             numeric,
        ftsit_avg_roll_mean                 numeric,
        ftsit_avg_roll_mean_ratio           numeric,
        alerts_score_avg_roll_mean          numeric,
        alerts_score_avg_roll_mean_ratio    numeric,
        dta_avg_roll_mean                   numeric,
        dta_avg_roll_mean_ratio             numeric,
        fta_avg_roll_mean                   numeric,
        fta_avg_roll_mean_ratio             numeric,
        lmlha_avg_roll_mean                 numeric,
        lmlha_avg_roll_mean_ratio           numeric,
        lmpa_avg_roll_mean                  numeric,
        lmpa_avg_roll_mean_ratio            numeric,
        pva_avg_roll_mean                   numeric,
        pva_avg_roll_mean_ratio             numeric,
        sa_avg_roll_mean                    numeric,
        sa_avg_roll_mean_ratio              numeric,
        score_avg_roll_mean                 numeric,
        score_avg_roll_mean_ratio           numeric,
        wca_avg_roll_mean                   numeric,
        wca_avg_roll_mean_ratio             numeric,
        wea_avg_roll_mean                   numeric,
        wea_avg_roll_mean_ratio             numeric,
        wta_avg_roll_mean                   numeric,
        wta_avg_roll_mean_ratio             numeric,
        wtmtlpb_avg_roll_mean               numeric,
        wtmtlpb_avg_roll_mean_ratio         numeric,
        wtmtlpf_avg_roll_mean               numeric,
        wtmtlpf_avg_roll_mean_ratio         numeric,
        wtsbmt_avg_roll_mean                numeric,
        wtsbmt_avg_roll_mean_ratio          numeric,
        wtsfmt_avg_roll_mean                numeric,
        wtsfmt_avg_roll_mean_ratio          numeric,
        wtsfrtalbp_avg_roll_mean            numeric,
        wtsfrtalbp_avg_roll_mean_ratio      numeric,
        wtsfsp_avg_roll_mean                numeric,
        wtsfsp_avg_roll_mean_ratio          numeric,
        wva_avg_roll_mean                   numeric,
        wva_avg_roll_mean_ratio             numeric
);


-- read csv file
copy imp_tse_health_index(
   id,
   created_at,
   updated_at,
   location,
   series,
   lin,
   plant,
   station,
   robot,
   controller,
   tool,
   stud,
   stud_extension,
   day,
   weld_count,
   bodyshop_count,
   bodyshop_fp_count,
   bodyshop_tp_count,
   assembly_shop_count,
   alerts_count,
   health,
   extension_id,
   stud_id,
   tool_id,
   tse_count,
   wops_count,
   alerts_score_avg,
   score_avg,
   ftsit_avg,
   dta_avg,
   fta_avg,
   lmlha_avg,
   lmpa_avg,
   pva_avg,
   sa_avg,
   wca_avg,
   wea_avg,
   wta_avg,
   wtmtlpb_avg,
   wtmtlpf_avg,
   wtsbmt_avg,
   wtsfmt_avg,
   wtsfrtalbp_avg,
   wtsfsp_avg,
   wva_avg,
   ftsit_avg_roll_mean,
   ftsit_avg_roll_mean_ratio,
   alerts_score_avg_roll_mean,
   alerts_score_avg_roll_mean_ratio,
   dta_avg_roll_mean,
   dta_avg_roll_mean_ratio,
   fta_avg_roll_mean,
   fta_avg_roll_mean_ratio,
   lmlha_avg_roll_mean,
   lmlha_avg_roll_mean_ratio,
   lmpa_avg_roll_mean,
   lmpa_avg_roll_mean_ratio,
   pva_avg_roll_mean,
   pva_avg_roll_mean_ratio,
   sa_avg_roll_mean,
   sa_avg_roll_mean_ratio,
   score_avg_roll_mean,
   score_avg_roll_mean_ratio,
   wca_avg_roll_mean,
   wca_avg_roll_mean_ratio,
   wea_avg_roll_mean,
   wea_avg_roll_mean_ratio,
   wta_avg_roll_mean,
   wta_avg_roll_mean_ratio,
   wtmtlpb_avg_roll_mean,
   wtmtlpb_avg_roll_mean_ratio,
   wtmtlpf_avg_roll_mean,
   wtmtlpf_avg_roll_mean_ratio,
   wtsbmt_avg_roll_mean,
   wtsbmt_avg_roll_mean_ratio,
   wtsfmt_avg_roll_mean,
   wtsfmt_avg_roll_mean_ratio,
   wtsfrtalbp_avg_roll_mean,
   wtsfrtalbp_avg_roll_mean_ratio,
   wtsfsp_avg_roll_mean,
   wtsfsp_avg_roll_mean_ratio,
   wva_avg_roll_mean,
   wva_avg_roll_mean_ratio)
FROM '/Users/guillem/Data/Customers/Daimler/health_index/tse_health_index.csv' DELIMITER ',' CSV HEADER;

drop table if exists tse_health_index;
create table tse_health_index(
      id varchar(100),
      stud_id varchar(100),
      tool_id varchar(100),
      extension_id varchar(100),
      day date,
      weld_count numeric,
      bodyshop_count numeric,
      bodyshop_fp_count numeric,
      bodyshop_tp_count numeric,
      assembly_shop_count numeric,
      alerts_count numeric,
      tse_count numeric,
      wops_count numeric,
      health numeric,
      alerts_score_avg numeric,
      score_avg numeric,
      ftsit_avg numeric,
      dta_avg numeric,
      fta_avg numeric,
      lmlha_avg numeric,
      lmpa_avg numeric,
      pva_avg numeric,
      sa_avg numeric,
      wca_avg numeric,
      wea_avg numeric,
      wta_avg numeric,
      wtmtlpb_avg numeric,
      wtmtlpf_avg numeric,
      wtsbmt_avg numeric,
      wtsfmt_avg numeric,
      wtsfrtalbp_avg numeric,
      wtsfsp_avg numeric,
      wva_avg numeric,
      ftsit_avg_roll_mean numeric,
      ftsit_avg_roll_mean_ratio numeric,
      alerts_score_avg_roll_mean numeric,
      alerts_score_avg_roll_mean_ratio numeric,
      dta_avg_roll_mean numeric,
      dta_avg_roll_mean_ratio numeric,
      fta_avg_roll_mean numeric,
      fta_avg_roll_mean_ratio numeric,
      lmlha_avg_roll_mean numeric,
      lmlha_avg_roll_mean_ratio numeric,
      lmpa_avg_roll_mean numeric,
      lmpa_avg_roll_mean_ratio numeric,
      pva_avg_roll_mean numeric,
      pva_avg_roll_mean_ratio numeric,
      sa_avg_roll_mean numeric,
      sa_avg_roll_mean_ratio numeric,
      score_avg_roll_mean numeric,
      score_avg_roll_mean_ratio numeric,
      wca_avg_roll_mean numeric,
      wca_avg_roll_mean_ratio numeric,
      wea_avg_roll_mean numeric,
      wea_avg_roll_mean_ratio numeric,
      wta_avg_roll_mean numeric,
      wta_avg_roll_mean_ratio numeric,
      wtmtlpb_avg_roll_mean numeric,
      wtmtlpb_avg_roll_mean_ratio numeric,
      wtmtlpf_avg_roll_mean numeric,
      wtmtlpf_avg_roll_mean_ratio numeric,
      wtsbmt_avg_roll_mean numeric,
      wtsbmt_avg_roll_mean_ratio numeric,
      wtsfmt_avg_roll_mean numeric,
      wtsfmt_avg_roll_mean_ratio numeric,
      wtsfrtalbp_avg_roll_mean numeric,
      wtsfrtalbp_avg_roll_mean_ratio numeric,
      wtsfsp_avg_roll_mean numeric,
      wtsfsp_avg_roll_mean_ratio numeric,
      wva_avg_roll_mean numeric,
      wva_avg_roll_mean_ratio numeric);

insert into tse_health_index(
       id,
       stud_id,
       tool_id,
       extension_id,
       day,
       weld_count,
       bodyshop_count,
       bodyshop_fp_count,
       bodyshop_tp_count,
       assembly_shop_count,
       alerts_count,
       tse_count,
       wops_count,
       health,
       alerts_score_avg,
       score_avg,
       ftsit_avg,
       dta_avg,
       fta_avg,
       lmlha_avg,
       lmpa_avg,
       pva_avg,
       sa_avg,
       wca_avg,
       wea_avg,
       wta_avg,
       wtmtlpb_avg,
       wtmtlpf_avg,
       wtsbmt_avg,
       wtsfmt_avg,
       wtsfrtalbp_avg,
       wtsfsp_avg,
       wva_avg,
       ftsit_avg_roll_mean,
       ftsit_avg_roll_mean_ratio,
       alerts_score_avg_roll_mean,
       alerts_score_avg_roll_mean_ratio,
       dta_avg_roll_mean,
       dta_avg_roll_mean_ratio,
       fta_avg_roll_mean,
       fta_avg_roll_mean_ratio,
       lmlha_avg_roll_mean,
       lmlha_avg_roll_mean_ratio,
       lmpa_avg_roll_mean,
       lmpa_avg_roll_mean_ratio,
       pva_avg_roll_mean,
       pva_avg_roll_mean_ratio,
       sa_avg_roll_mean,
       sa_avg_roll_mean_ratio,
       score_avg_roll_mean,
       score_avg_roll_mean_ratio,
       wca_avg_roll_mean,
       wca_avg_roll_mean_ratio,
       wea_avg_roll_mean,
       wea_avg_roll_mean_ratio,
       wta_avg_roll_mean,
       wta_avg_roll_mean_ratio,
       wtmtlpb_avg_roll_mean,
       wtmtlpb_avg_roll_mean_ratio,
       wtmtlpf_avg_roll_mean,
       wtmtlpf_avg_roll_mean_ratio,
       wtsbmt_avg_roll_mean,
       wtsbmt_avg_roll_mean_ratio,
       wtsfmt_avg_roll_mean,
       wtsfmt_avg_roll_mean_ratio,
       wtsfrtalbp_avg_roll_mean,
       wtsfrtalbp_avg_roll_mean_ratio,
       wtsfsp_avg_roll_mean,
       wtsfsp_avg_roll_mean_ratio,
       wva_avg_roll_mean,
       wva_avg_roll_mean_ratio)
select 
       a.id,
       a.stud_id,
       a.tool_id,
       a.extension_id,
       to_date(a.day,'YYYY-MM-DD'),
       a.weld_count::numeric,
       a.bodyshop_count,
       a.bodyshop_fp_count,
       a.bodyshop_tp_count,
       a.assembly_shop_count,
       a.alerts_count,
       a.tse_count,
       a.wops_count,
       a.health,
       a.alerts_score_avg,
       a.score_avg,
       a.ftsit_avg,
       a.dta_avg,
       a.fta_avg,
       a.lmlha_avg,
       a.lmpa_avg,
       a.pva_avg,
       a.sa_avg,
       a.wca_avg,
       a.wea_avg,
       a.wta_avg,
       a.wtmtlpb_avg,
       a.wtmtlpf_avg,
       a.wtsbmt_avg,
       a.wtsfmt_avg,
       a.wtsfrtalbp_avg,
       a.wtsfsp_avg,
       a.wva_avg,
       a.ftsit_avg_roll_mean,
       a.ftsit_avg_roll_mean_ratio,
       a.alerts_score_avg_roll_mean,
       a.alerts_score_avg_roll_mean_ratio,
       a.dta_avg_roll_mean,
       a.dta_avg_roll_mean_ratio,
       a.fta_avg_roll_mean,
       a.fta_avg_roll_mean_ratio,
       a.lmlha_avg_roll_mean,
       a.lmlha_avg_roll_mean_ratio,
       a.lmpa_avg_roll_mean,
       a.lmpa_avg_roll_mean_ratio,
       a.pva_avg_roll_mean,
       a.pva_avg_roll_mean_ratio,
       a.sa_avg_roll_mean,
       a.sa_avg_roll_mean_ratio,
       a.score_avg_roll_mean,
       a.score_avg_roll_mean_ratio,
       a.wca_avg_roll_mean,
       a.wca_avg_roll_mean_ratio,
       a.wea_avg_roll_mean,
       a.wea_avg_roll_mean_ratio,
       a.wta_avg_roll_mean,
       a.wta_avg_roll_mean_ratio,
       a.wtmtlpb_avg_roll_mean,
       a.wtmtlpb_avg_roll_mean_ratio,
       a.wtmtlpf_avg_roll_mean,
       a.wtmtlpf_avg_roll_mean_ratio,
       a.wtsbmt_avg_roll_mean,
       a.wtsbmt_avg_roll_mean_ratio,
       a.wtsfmt_avg_roll_mean,
       a.wtsfmt_avg_roll_mean_ratio,
       a.wtsfrtalbp_avg_roll_mean,
       a.wtsfrtalbp_avg_roll_mean_ratio,
       a.wtsfsp_avg_roll_mean,
       a.wtsfsp_avg_roll_mean_ratio,
       a.wva_avg_roll_mean,
       a.wva_avg_roll_mean_ratio
from imp_tse_health_index a;

create index inx_tsehi_toolday on tse_health_index(tool_id, day);
create index inx_tsehi_extensionday on tse_health_index(extension_id, day);

------------------------------------------------------------------
----- IMP_TOOL_COUNTERS
------------------------------------------------------------------
drop table if exists imp_tool_counters;
create table imp_tool_counters(
     uniqueid       varchar(100),
     timestamp_txt  varchar(100),
     total_welds    numeric,
     total_wops     numeric
);

-- read csv file
copy imp_tool_counters(
   total_wops,
   uniqueid,
   timestamp_txt,
   total_welds)
FROM '/Users/guillem/Data/Customers/Daimler/health_index/tool_counts_extended.csv' DELIMITER ',' CSV HEADER;

create index inx_imptoocounters_uniqueidtime on imp_tool_counters(uniqueid,timestamp_txt);

------------------------------------------------------------------------------------------------------------
------------------ create online table with proper types
------------------------------------------------------------------------------------------------------------
drop table if exists tool_counters;
create table tool_counters(
  uniqueid      varchar(100),
  moment        timestamp,
  total_welds   numeric,
  total_wops    numeric
);

insert into tool_counters(
   uniqueid,
   moment,
   total_welds,
   total_wops)
select 
   a.uniqueid,
   to_timestamp(a.timestamp_txt,'YYYY-MM-DD'),
   a.total_welds,
   a.total_wops
from imp_tool_counters a;

create index inx_toolcounters_tooltime on tool_counters(uniqueid,moment);

------------------------------------
---- daily aggregate data
------------------------------------
drop table if exists tool_counters_day;
create table tool_counters_day as
   select uniqueid, moment::date as day, max(total_welds) as total_welds, max(total_wops) as total_wops
   from tool_counters
   group by uniqueid, moment::date;

create index inx_toolcountersday_daytool on tool_counters_day(uniqueid, day);

-- drop full counters tables for more space
drop table if exists tool_counters;
drop table if exists imp_tool_counters;

----------------------------------------
-------- Toolcodes
----------------------------------------
drop table if exists tool_codes;
create table tool_codes(
     uniqueid       varchar(100),
     tool_id        varchar(100)
);

-- read csv file
copy tool_codes(
   uniqueid,
   tool_id
)
FROM '/Users/guillem/Data/Customers/Daimler/health_index/toolcodes.csv' DELIMITER ',' CSV HEADER;

create index inx_toolcodes_uniqueid on tool_codes(uniqueid);
create index inx_toolcodes_toolid on tool_codes(tool_id);


----------------------------------------------------------------------------
---------------------            CLEAN DATA            ---------------------
----------------------------------------------------------------------------

-- clean old data
delete from tse_health_index where day < '2020-01-01';
-- clean days when welds are very low
delete from tse_health_index a 
where exists (select 1
              from health_index b
              where b.tool_id = a.tool_id and
                    b.day = a.day and
                    b.weld_count < 200);

-- clean extensions with a low amount of welds
delete from tse_health_index a
where exists (select 1 
              from (select b.extension_id, count(1) ct from tse_health_index b group by b.extension_id) x
              where a.extension_id = x.extension_id and x.ct < 50);

-- clean old data
delete from health_index where day < '2020-01-01';
-- clean when welds are very low
delete from health_index where weld_count < 200;
-- clean weekends
-- delete from health_index where extract(DOW from day) in (0,6);





create index inx_healthindex_toolday on health_index(tool_id, day);


